dist: bionic
language: go
go:
  - 1.13.x
services:
  - postgresql
addons:
  postgresql: "10"
git:
  depth: 1
notifications:
  email: false
before_script:
  - psql -c 'create database user_service;' -U postgres
  - psql -c 'create extension if not exists "uuid-ossp";' -U postgres
  - go vet ./...
  - go run migrations/*.go
script:
  - go test ./internal/...
