dist: bionic
language: go
go:
  - 1.13.x
services:
  - postgresql
  - docker
addons:
  postgresql: "10"
git:
  depth: 1
notifications:
  email: false
before_script:
  - psql -c 'create database user_service;' -U postgres
  - go vet ./...
  - go run migrations/*.go
script:
  - go test ./internal/...
before_deploy:
  - docker build -t quay.io/danielmunro/otto-user-service:$(git rev-parse --short ${TRAVIS_COMMIT}) -t quay.io/danielmunro/otto-user-service:latest .
deploy:
  - provider: script
    script: bash bin/docker_push