apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-service
  description: Otto user service
  links:
    - url: https://github.com/danielmunro/otto-user-service
      title: Git Repository
spec:
  type: openapi
  lifecycle: production
  owner: dev-team
  definition:
    $text: https://github.com/danielmunro/otto-user-service/blob/main/api.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: user-service-db
  description: Otto user service DB
spec:
  type: database
  lifecycle: production
  owner: dev-team
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aws-cognito
  description: AWS Cognito instance
spec:
  type: service
  lifecycle: production
  owner: dev-team
