version: "3"
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=otto
      - POSTGRES_PASSWORD=otto
      - POSTGRES_DB=user_service
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data