version: "3"
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    env_file:
      - .env
    ports:
      - "54321:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data