/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"time"
)

type User struct {

	Id int64 `json:"id,omitempty"`

	Uuid string `json:"uuid"`

	Name string `json:"name,omitempty"`

	CurrentEmail string `json:"current_email,omitempty"`

	CurrentPassword string `json:"current_password,omitempty"`

	Birthday string `json:"birthday,omitempty"`

	Verified bool `json:"verified,omitempty"`

	Created time.Time `json:"created,omitempty"`

	Updated time.Time `json:"updated,omitempty"`

	Emails []Email `json:"emails,omitempty"`

	Passwords []Password `json:"passwords,omitempty"`
}
