/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

type VerifiedStatus string

// List of VerifiedStatus
const (
	UNVERIFIED VerifiedStatus = "unverified"
	VERIFIED VerifiedStatus = "verified"
)
